include: package:lints/recommended.yaml

linter:
  rules:
    - camel_case_types

analyzer:
  exclude:
    - .dart_tool/**
    - build/**
    - test/**/generated/**
    - lib/**/generated/**
    - bin/**/generated/**
    - example/**/generated/**
    - tool/**/generated/**
